channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - snakemake-minimal==5.7.1
  - curl
  - bwa==0.7.17
  - elprep==5.0.1
  - pip
  - pip:
    - jsonschema<4
    - warlock==1.3.3
    - pytest
    - pytest-cov
    - pytest-profiling
    - coverage
    - pyyaml
    - argh
    - watchdog
    - bifrostlib
    - -e .