#-Basic info----------------------------------------------------------------------------------------
display_name: salmonella_subspecies_dtartrate
name: salmonella_subspecies_dtartrate__v1.0.5
version:
  schema: ["v2_1_0"]
  code: v1.0.5
#---------------------------------------------------------------------------------------------------

#-Details-------------------------------------------------------------------------------------------
details:
  target: [sample]
  description: >
    Predicts Salmonella subspecies and D-tartrate SNP.
#---------------------------------------------------------------------------------------------------

#-Install-------------------------------------------------------------------------------------------
install:
  path: # Set by install program
  dockerfile: docker://ssidk/bifrost_salmonella_subspecies_dtartrate
# None
#---------------------------------------------------------------------------------------------------

#-Category info-------------------------------------------------------------------------------------
category: [serotype]
#---------------------------------------------------------------------------------------------------

#-Options-------------------------------------------------------------------------------------------
#options:
#  min_num_reads: 10000
#---------------------------------------------------------------------------------------------------

#-Required resource files---------------------------------------------------------------------------
resources:
  dtartrate_db: "/resources/d_Tartrate/srst2_d_Tartrate.fasta"
  subspecies_reference: "/resources/salmonella_subspecies_STs.txt"
  mlst_db: "/resources/salmonella/"
#---------------------------------------------------------------------------------------------------

#-Requirements to run component---------------------------------------------------------------------
requirements:
  sample:
    categories:
      mlst:
        summary:
          sequence_type:
      species_detection:
        summary:
          species: Salmonella enterica
  components:
    analyzer:
      status:
#---------------------------------------------------------------------------------------------------

#-DB Value changes (excluding component output)-----------------------------------------------------
# db_values_changes:
#   files: []
#   sample:
#     categories:
#       size_check:
#         summary:  # see sample_component summary
#         component:
#           _id: 
#           date:  # ObjectId
#     report:
#   sample_component:
#     summary:
#       has_min_num_of_reads:  # Boolean
#     results:
#       min_read_check/data_yaml: {}
#---------------------------------------------------------------------------------------------------
